<?php
/**
 * Catalog Health Scanner for WooCommerce - PDF Audit Report Class
 *
 * Cover page, overall score, category breakdown, severity distribution,
 * top issues, comparison against the previous scan, with a white-label
 * option (agency name, logo, custom footer) — spec section 12.
 *
 * Download follows the admin GET action link pattern: nonce in the URL,
 * nonce + capability in the handler.
 *
 * @version 1.0.0
 * @since   1.0.0
 *
 * @author  WPFactory
 */

defined( 'ABSPATH' ) || exit;

if ( ! class_exists( 'WPFCHS_Report' ) ) :

class WPFCHS_Report {

	/**
	 * PDF writer for the current build.
	 *
	 * @var     WPFCHS_PDF
	 * @since   1.0.0
	 */
	protected $pdf;

	/**
	 * Score band for the current report (drives accent colour).
	 *
	 * @var     array
	 * @since   1.0.0
	 */
	protected $band;

	/**
	 * Branding for the current report.
	 *
	 * @var     array
	 * @since   1.0.0
	 */
	protected $brand;

	/**
	 * Running page number.
	 *
	 * @var     int
	 * @since   1.0.0
	 */
	protected $page = 0;

	/**
	 * Constructor.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 */
	function __construct() {
		add_action( 'admin_init', array( $this, 'maybe_download' ) );
	}

	/**
	 * get_url.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 *
	 * @param   int $scan_id 0 = latest completed scan.
	 * @return  string
	 */
	function get_url( $scan_id = 0 ) {
		return wp_nonce_url(
			add_query_arg(
				array(
					'wpfchs_report' => 'pdf',
					'scan_id'       => absint( $scan_id ),
				),
				admin_url( 'admin.php?page=wpfchs' )
			),
			'wpfchs_report'
		);
	}

	/**
	 * maybe_download.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 */
	function maybe_download() {

		if ( ! isset( $_GET['wpfchs_report'] ) ) {
			return;
		}

		if (
			! isset( $_GET['_wpnonce'] ) ||
			! wp_verify_nonce( sanitize_text_field( wp_unslash( $_GET['_wpnonce'] ) ), 'wpfchs_report' ) ||
			! current_user_can( wpfchs()->core->get_capability() )
		) {
			wp_die( esc_html__( 'Link expired.', 'catalog-health-scanner-for-woocommerce' ) );
		}

		// The PDF report is Pro. The UI renders a locked button instead of
		// this URL in the free build; this is the enforcement behind it.
		if ( ! wpfchs()->is_pro() ) {
			wp_die(
				esc_html__( 'The PDF report is a Pro feature.', 'catalog-health-scanner-for-woocommerce' ) .
				' <a href="' . esc_url( WPFCHS_Upgrade::URL ) . '" target="_blank">' .
				esc_html__( 'Unlock with Pro', 'catalog-health-scanner-for-woocommerce' ) . '</a>',
				esc_html__( 'Pro feature', 'catalog-health-scanner-for-woocommerce' ),
				array( 'response' => 403, 'back_link' => true )
			);
		}

		$scan_id = isset( $_GET['scan_id'] ) ? absint( wp_unslash( $_GET['scan_id'] ) ) : 0;
		$scan    = ( $scan_id ? wpfchs()->core->scanner->get_scan( $scan_id ) : wpfchs()->core->scanner->get_last_completed() );

		if ( ! $scan || 'complete' !== $scan->status ) {
			wp_die( esc_html__( 'No completed scan to report on.', 'catalog-health-scanner-for-woocommerce' ) );
		}

		$pdf = $this->build( $scan );

		nocache_headers();
		header( 'Content-Type: application/pdf' );
		header( 'Content-Disposition: attachment; filename=catalog-health-report-' . gmdate( 'Y-m-d', strtotime( $scan->completed_at ) ) . '.pdf' );
		header( 'Content-Length: ' . strlen( $pdf ) );

		echo $pdf; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Binary PDF stream, not HTML.
		exit;

	}

	/**
	 * Branding settings with fallbacks.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 *
	 * @return  array
	 */
	function get_branding() {
		$branding = wp_parse_args(
			(array) get_option( 'wpfchs_branding', array() ),
			array(
				'agency_name' => '',
				'logo_id'     => 0,
				'footer'      => '',
			)
		);
		if ( '' === $branding['agency_name'] ) {
			$branding['agency_name'] = wp_specialchars_decode( get_bloginfo( 'name' ), ENT_QUOTES );
		}
		if ( '' === $branding['footer'] ) {
			$branding['footer'] = __( 'Generated by Catalog Health Scanner for WooCommerce', 'catalog-health-scanner-for-woocommerce' );
		}
		return $branding;
	}

	/**
	 * Builds the report PDF for a scan.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 *
	 * @param   object $scan
	 * @return  string PDF bytes.
	 */
	function build( $scan ) {

		$core       = wpfchs()->core;
		$this->pdf  = new WPFCHS_PDF();
		$this->page = 0;

		$branding   = $this->get_branding();
		$data       = json_decode( (string) $scan->score_data, true );
		$categories = (array) ( $data['categories'] ?? array() );
		$labels     = $core->checks->get_categories();
		$score      = (float) $scan->score;
		$band        = $core->scores->get_band( $score );
		$this->band  = $band;
		$this->brand = $branding;
		$date       = get_date_from_gmt( $scan->completed_at, get_option( 'date_format' ) );

		$severities = array(
			'critical' => array( __( 'Critical', 'catalog-health-scanner-for-woocommerce' ), '#d63638' ),
			'high'     => array( __( 'High', 'catalog-health-scanner-for-woocommerce' ), '#e65054' ),
			'medium'   => array( __( 'Medium', 'catalog-health-scanner-for-woocommerce' ), '#dba617' ),
			'low'      => array( __( 'Low', 'catalog-health-scanner-for-woocommerce' ), '#646970' ),
		);

		$sev_counts = array();
		foreach ( $severities as $severity => $meta ) {
			$sev_counts[ $severity ] = $core->issues->count(
				array(
					'status'   => 'open',
					'severity' => $severity,
				)
			);
		}

		$this->render_cover( $scan, $score, $band, $branding, $date, $sev_counts, $categories, $labels );
		$this->render_scorecard( $core, $categories, $labels, $severities, $sev_counts );
		$this->render_findings( $core, $labels, $severities );

		return $this->pdf->output();

	}

	/**
	 * Cover page: brand, hero score with meter, four stat tiles, severity
	 * chips, and the trend against the previous scan.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 */
	protected function render_cover( $scan, $score, $band, $branding, $date, $sev_counts, $categories, $labels ) {

		$pdf  = $this->pdf;
		$core = wpfchs()->core;
		$this->start_page();

		// Brand band across the top.
		$pdf->rect( 0, 0, WPFCHS_PDF::PAGE_W, 90, '#1d2327' );

		$logo_shift = 0;
		if ( $branding['logo_id'] ) {
			$file = get_attached_file( $branding['logo_id'] );
			if ( $file && file_exists( $file ) ) {
				$blob = file_get_contents( $file ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Local attachment file read, not a remote URL.
				if ( $blob && $pdf->image( $blob, 60, 26, 110 ) ) {
					$logo_shift = 130;
				}
			}
		}
		$pdf->text( 60 + $logo_shift, 44, $branding['agency_name'], 16, true, '#ffffff' );
		$pdf->text( 60 + $logo_shift, 64, __( 'Catalog Health Audit', 'catalog-health-scanner-for-woocommerce' ), 11, false, '#c3c4c7' );
		$pdf->text( WPFCHS_PDF::PAGE_W - 60, 54, wp_parse_url( home_url(), PHP_URL_HOST ) . '  ·  ' . $date, 10, false, '#c3c4c7', 'right' );

		// Hero score.
		$pdf->text( 60, 190, wc_format_decimal( $score, 0 ) . '%', 84, true, $band['color'] );
		$pdf->text( 250, 150, $band['label'], 20, true, $band['color'] );
		$pdf->text( 250, 174, sprintf(
			/* translators: %1$s: products scanned, %2$s: issues found. */
			__( '%1$s products scanned  ·  %2$s open issues', 'catalog-health-scanner-for-woocommerce' ),
			number_format_i18n( (int) $scan->products_scanned ),
			number_format_i18n( (int) $scan->issues_found )
		), 11, false, '#646970' );

		$profiles = $core->profiles->get_all();
		$pdf->text( 250, 192, sprintf(
			/* translators: %s: scan profile name. */
			__( 'Profile: %s', 'catalog-health-scanner-for-woocommerce' ),
			( $profiles[ $scan->profile ]['label'] ?? $scan->profile )
		), 11, false, '#646970' );

		// Anything excluded from the score has to be declared on the cover.
		// This document gets handed to clients; a score that quietly omits
		// ignored findings or skipped products would misrepresent the store.
		$ignored = $core->issues->count( array( 'status' => 'ignored' ) );
		$skipped = $core->scanner->get_skipped_count( $scan );
		$caveats = array();
		if ( $ignored > 0 ) {
			$caveats[] = sprintf(
				/* translators: %s: number of ignored issues. */
				_n( '%s issue ignored', '%s issues ignored', $ignored, 'catalog-health-scanner-for-woocommerce' ),
				number_format_i18n( $ignored )
			);
		}
		if ( $skipped > 0 ) {
			$caveats[] = sprintf(
				/* translators: %s: number of products skipped. */
				_n( '%s product not checked', '%s products not checked', $skipped, 'catalog-health-scanner-for-woocommerce' ),
				number_format_i18n( $skipped )
			);
		}
		if ( ! empty( $caveats ) ) {
			$pdf->text(
				250,
				210,
				__( 'Excluded from this score:', 'catalog-health-scanner-for-woocommerce' ) . ' ' . implode( ', ', $caveats ),
				9,
				false,
				'#b26200'
			);
		}

		// Score meter.
		$pdf->rect( 60, 210, 475, 10, '#e5e5e6' );
		$pdf->rect( 60, 210, 475 * max( 0, min( 1, $score / 100 ) ), 10, $band['color'] );

		// Stat tiles.
		$critical  = $sev_counts['critical'];
		$previous  = $core->schedule->get_previous_score( (int) $scan->id );
		$delta_str = ( null !== $previous ? ( ( $score - $previous >= 0 ? '+' : '' ) . wc_format_decimal( $score - $previous, 1 ) ) : '—' );
		$delta_col = ( null === $previous ? '#646970' : ( $score - $previous >= 0 ? '#00812c' : '#d63638' ) );

		$applicable = 0;
		foreach ( $categories as $cat ) {
			$applicable++;
		}

		$tiles = array(
			array( number_format_i18n( (int) $scan->products_scanned ), __( 'Products', 'catalog-health-scanner-for-woocommerce' ), '#1d2327' ),
			array( number_format_i18n( (int) $scan->issues_found ), __( 'Open issues', 'catalog-health-scanner-for-woocommerce' ), '#1d2327' ),
			array( number_format_i18n( $critical ), __( 'Critical', 'catalog-health-scanner-for-woocommerce' ), ( $critical > 0 ? '#d63638' : '#00812c' ) ),
			array( $delta_str, __( 'vs last scan', 'catalog-health-scanner-for-woocommerce' ), $delta_col ),
		);
		$tile_w = ( 475 - 3 * 13 ) / 4;
		$tx     = 60;
		foreach ( $tiles as $tile ) {
			$pdf->rect( $tx, 250, $tile_w, 70, '#f6f7f7' );
			$pdf->rect( $tx, 250, $tile_w, 3, $band['color'] );
			$pdf->text( $tx + $tile_w / 2, 292, (string) $tile[0], 26, true, $tile[2], 'center' );
			$pdf->text( $tx + $tile_w / 2, 310, (string) $tile[1], 9, false, '#646970', 'center' );
			$tx += $tile_w + 13;
		}

		// Severity chips.
		$pdf->text( 60, 360, __( 'Open issues by severity', 'catalog-health-scanner-for-woocommerce' ), 13, true );
		$sx = 60;
		foreach ( array(
			'critical' => array( __( 'Critical', 'catalog-health-scanner-for-woocommerce' ), '#d63638' ),
			'high'     => array( __( 'High', 'catalog-health-scanner-for-woocommerce' ), '#e65054' ),
			'medium'   => array( __( 'Medium', 'catalog-health-scanner-for-woocommerce' ), '#dba617' ),
			'low'      => array( __( 'Low', 'catalog-health-scanner-for-woocommerce' ), '#646970' ),
		) as $severity => $meta ) {
			$pdf->rect( $sx, 375, 11, 11, $meta[1] );
			$pdf->text( $sx + 17, 384, $meta[0] . ': ' . number_format_i18n( $sev_counts[ $severity ] ), 11 );
			$sx += 118;
		}

		// Most-severe findings teaser.
		$open_counts = $core->issues->count_open_by_check();
		$rows        = array();
		foreach ( $open_counts as $check_id => $count ) {
			$check = $core->checks->get( $check_id );
			if ( $check ) {
				$rows[] = array( 'check' => $check, 'count' => $count, 'weight' => $count * $check->get_weight() );
			}
		}
		usort( $rows, function ( $a, $b ) { return $b['weight'] <=> $a['weight']; } );

		if ( ! empty( $rows ) ) {
			$pdf->text( 60, 430, __( 'What to fix first', 'catalog-health-scanner-for-woocommerce' ), 13, true );
			$y = 452;
			foreach ( array_slice( $rows, 0, 5 ) as $row ) {
				$sev = $row['check']->get_severity();
				$col = array( 'critical' => '#d63638', 'high' => '#e65054', 'medium' => '#dba617', 'low' => '#646970' )[ $sev ] ?? '#646970';
				$pdf->rect( 60, $y - 8, 8, 8, $col );
				$pdf->text( 76, $y, $row['check']->get_label(), 11 );
				$pdf->text( 535, $y, sprintf(
					/* translators: %s: number of affected products. */
					__( '%s products', 'catalog-health-scanner-for-woocommerce' ),
					number_format_i18n( $row['count'] )
				), 10, false, '#646970', 'right' );
				$y += 22;
			}
		}

		$this->footer();

	}

	/**
	 * Scorecard page: per-category bars and the severity distribution.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 */
	protected function render_scorecard( $core, $categories, $labels, $severities, $sev_counts ) {

		$pdf = $this->pdf;
		$this->start_page( __( 'Category scorecard', 'catalog-health-scanner-for-woocommerce' ) );
		$y = 120;

		foreach ( $labels as $category_id => $label ) {
			if ( ! isset( $categories[ $category_id ] ) ) {
				continue;
			}
			$earned   = (float) $categories[ $category_id ]['earned'];
			$possible = (float) $categories[ $category_id ]['possible'];
			$cat_band = $core->scores->get_category_band( $earned, $possible );
			$percent  = ( $possible > 0 ? $earned / $possible : 1 );

			$pdf->text( 60, $y, $label, 11, true );
			$pdf->text( 320, $y, wc_format_decimal( $earned, 1 ) . ' / ' . wc_format_decimal( $possible, 0 ), 11, false, '#646970', 'right' );
			$pdf->rect( 340, $y - 8, 195, 8, '#e5e5e6' );
			$pdf->rect( 340, $y - 8, 195 * max( 0, min( 1, $percent ) ), 8, $cat_band['color'] );
			$y += 26;
		}

		$y += 24;
		$pdf->text( 60, $y, __( 'Severity distribution', 'catalog-health-scanner-for-woocommerce' ), 14, true );
		$y += 20;

		$total = array_sum( $sev_counts );
		if ( $total > 0 ) {
			$bx = 60;
			foreach ( $severities as $severity => $meta ) {
				$w = 475 * ( $sev_counts[ $severity ] / $total );
				if ( $w > 0 ) {
					$pdf->rect( $bx, $y, $w, 18, $meta[1] );
					$bx += $w;
				}
			}
			$y += 30;
		}

		$lx = 60;
		foreach ( $severities as $severity => $meta ) {
			$pdf->rect( $lx, $y - 9, 10, 10, $meta[1] );
			$pdf->text( $lx + 16, $y, $meta[0] . ': ' . number_format_i18n( $sev_counts[ $severity ] ), 11 );
			$lx += 118;
		}

		$this->footer();

	}

	/**
	 * Findings pages: every check with open issues, grouped by category,
	 * auto-paginated. This is the "cover all findings" section.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 */
	protected function render_findings( $core, $labels, $severities ) {

		$pdf         = $this->pdf;
		$open_counts = $core->issues->count_open_by_check();
		$last        = $core->admin->get_last_scan_data();
		$cat_scores  = $last['categories'];

		// Group check rows by category.
		$by_category = array();
		foreach ( $open_counts as $check_id => $count ) {
			$check = $core->checks->get( $check_id );
			if ( $check ) {
				$by_category[ $check->get_category() ][] = array( 'check' => $check, 'count' => $count );
			}
		}

		$this->start_page( __( 'All findings', 'catalog-health-scanner-for-woocommerce' ) );
		$y = 120;

		$severity_order = array( 'critical' => 0, 'high' => 1, 'medium' => 2, 'low' => 3 );

		if ( empty( $by_category ) ) {
			$pdf->text( 60, $y, __( 'No open issues. Every applicable check passed.', 'catalog-health-scanner-for-woocommerce' ), 12, false, '#00812c' );
			$this->footer();
			return;
		}

		foreach ( $labels as $category_id => $label ) {

			if ( empty( $by_category[ $category_id ] ) ) {
				continue;
			}

			$rows = $by_category[ $category_id ];
			usort( $rows, function ( $a, $b ) use ( $severity_order ) {
				$cmp = $severity_order[ $a['check']->get_severity() ] <=> $severity_order[ $b['check']->get_severity() ];
				return ( 0 !== $cmp ? $cmp : $b['count'] <=> $a['count'] );
			} );

			$y = $this->ensure_space( $y, 46 );

			// Category heading with its score fraction.
			$pdf->text( 60, $y, $label, 14, true );
			if ( isset( $cat_scores[ $category_id ] ) ) {
				$pdf->text( 535, $y, wc_format_decimal( $cat_scores[ $category_id ]['earned'], 1 ) . ' / ' . wc_format_decimal( $cat_scores[ $category_id ]['possible'], 0 ), 11, false, '#646970', 'right' );
			}
			$y += 8;
			$pdf->rect( 60, $y, 475, 0.7, '#dcdcde' );
			$y += 18;

			foreach ( $rows as $row ) {
				$y   = $this->ensure_space( $y, 22 );
				$sev = $row['check']->get_severity();
				$col = $severities[ $sev ][1];
				$pdf->rect( 60, $y - 8, 8, 8, $col );
				$pdf->text( 76, $y, $row['check']->get_label(), 10 );
				$pdf->text( 470, $y, $severities[ $sev ][0], 9, false, '#646970' );
				$pdf->text( 535, $y, number_format_i18n( $row['count'] ), 10, true, '#1d2327', 'right' );
				$y += 22;
			}
			$y += 14;
		}

		$this->footer();

	}

	/**
	 * Starts a new page: top brand rule, page counter, optional section title.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 *
	 * @param   string $title
	 */
	protected function start_page( $title = '' ) {
		$this->pdf->add_page();
		$this->page++;
		$this->pdf->rect( 0, 0, WPFCHS_PDF::PAGE_W, 8, $this->band['color'] );
		if ( '' !== $title ) {
			$this->pdf->text( 60, 70, $title, 20, true );
		}
	}

	/**
	 * Ensures $needed points of vertical space remain; otherwise closes the
	 * page and starts a continuation.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 *
	 * @param   float $y
	 * @param   float $needed
	 * @return  float New y cursor.
	 */
	protected function ensure_space( $y, $needed ) {
		if ( $y + $needed > WPFCHS_PDF::PAGE_H - 80 ) {
			$this->footer();
			$this->start_page();
			return 100;
		}
		return $y;
	}

	/**
	 * footer.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 */
	protected function footer() {
		$pdf = $this->pdf;
		$pdf->rect( 60, WPFCHS_PDF::PAGE_H - 60, WPFCHS_PDF::PAGE_W - 120, 0.7, '#dcdcde' );
		$pdf->text( 60, WPFCHS_PDF::PAGE_H - 42, $this->brand['footer'], 9, false, '#646970' );
		$pdf->text( WPFCHS_PDF::PAGE_W - 60, WPFCHS_PDF::PAGE_H - 42, (string) $this->page, 9, false, '#646970', 'right' );
	}

}

endif;

return new WPFCHS_Report();
