<?php
/**
 * Catalog Health Scanner for WooCommerce - PDF Audit Report Class
 *
 * Cover page, overall score, category breakdown, severity distribution,
 * top issues, comparison against the previous scan, with a white-label
 * option (agency name, logo, custom footer) — spec section 12.
 *
 * Download follows the admin GET action link pattern: nonce in the URL,
 * nonce + capability in the handler.
 *
 * @version 1.0.0
 * @since   1.0.0
 *
 * @author  WPFactory
 */

defined( 'ABSPATH' ) || exit;

if ( ! class_exists( 'WPFCHS_Report' ) ) :

class WPFCHS_Report {

	/**
	 * PDF writer for the current build.
	 *
	 * @var     WPFCHS_PDF
	 * @since   1.0.0
	 */
	protected $pdf;

	/**
	 * Score band for the current report (drives accent colour).
	 *
	 * @var     array
	 * @since   1.0.0
	 */
	protected $band;

	/**
	 * Branding for the current report.
	 *
	 * @var     array
	 * @since   1.0.0
	 */
	protected $brand;

	/**
	 * Running page number.
	 *
	 * @var     int
	 * @since   1.0.0
	 */
	protected $page = 0;

	/**
	 * Constructor.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 */
	function __construct() {
		add_action( 'admin_init', array( $this, 'maybe_download' ) );
	}

	/**
	 * get_url.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 *
	 * @param   int $scan_id 0 = latest completed scan.
	 * @return  string
	 */
	function get_url( $scan_id = 0 ) {
		return wp_nonce_url(
			add_query_arg(
				array(
					'wpfchs_report' => 'pdf',
					'scan_id'       => absint( $scan_id ),
				),
				admin_url( 'admin.php?page=wpfchs' )
			),
			'wpfchs_report'
		);
	}

	/**
	 * maybe_download.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 */
	function maybe_download() {

		if ( ! isset( $_GET['wpfchs_report'] ) ) {
			return;
		}

		if (
			! isset( $_GET['_wpnonce'] ) ||
			! wp_verify_nonce( sanitize_text_field( wp_unslash( $_GET['_wpnonce'] ) ), 'wpfchs_report' ) ||
			! current_user_can( wpfchs()->core->get_capability() )
		) {
			wp_die( esc_html__( 'Link expired.', 'catalog-health-scanner-for-woocommerce' ) );
		}

		// The PDF report is Pro. The UI renders a locked button instead of
		// this URL in the free build; this is the enforcement behind it.
		if ( ! wpfchs()->is_pro() ) {
			wp_die(
				esc_html__( 'The PDF report is a Pro feature.', 'catalog-health-scanner-for-woocommerce' ) .
				' <a href="' . esc_url( WPFCHS_Upgrade::URL ) . '" target="_blank">' .
				esc_html__( 'Unlock with Pro', 'catalog-health-scanner-for-woocommerce' ) . '</a>',
				esc_html__( 'Pro feature', 'catalog-health-scanner-for-woocommerce' ),
				array( 'response' => 403, 'back_link' => true )
			);
		}

		$scan_id = isset( $_GET['scan_id'] ) ? absint( wp_unslash( $_GET['scan_id'] ) ) : 0;
		$scan    = ( $scan_id ? wpfchs()->core->scanner->get_scan( $scan_id ) : wpfchs()->core->scanner->get_last_completed() );

		if ( ! $scan || 'complete' !== $scan->status ) {
			wp_die( esc_html__( 'No completed scan to report on.', 'catalog-health-scanner-for-woocommerce' ) );
		}

		$pdf = $this->build( $scan );

		nocache_headers();
		header( 'Content-Type: application/pdf' );
		header( 'Content-Disposition: attachment; filename=catalog-health-report-' . gmdate( 'Y-m-d', strtotime( $scan->completed_at ) ) . '.pdf' );
		header( 'Content-Length: ' . strlen( $pdf ) );

		echo $pdf; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Binary PDF stream, not HTML.
		exit;

	}

	/**
	 * Branding settings with fallbacks.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 *
	 * @return  array
	 */
	function get_branding() {
		$branding = wp_parse_args(
			(array) get_option( 'wpfchs_branding', array() ),
			array(
				'agency_name' => '',
				'logo_id'     => 0,
				'footer'      => '',
			)
		);
		if ( '' === $branding['agency_name'] ) {
			$branding['agency_name'] = wp_specialchars_decode( get_bloginfo( 'name' ), ENT_QUOTES );
		}
		if ( '' === $branding['footer'] ) {
			$branding['footer'] = __( 'Generated by Catalog Health Scanner for WooCommerce', 'catalog-health-scanner-for-woocommerce' );
		}
		return $branding;
	}

	/**
	 * Builds the report PDF for a scan.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 *
	 * @param   object $scan
	 * @return  string PDF bytes.
	 */
	function build( $scan ) {

		$core       = wpfchs()->core;
		$this->pdf  = new WPFCHS_PDF();
		$this->page = 0;

		$branding   = $this->get_branding();
		$data       = json_decode( (string) $scan->score_data, true );
		$categories = (array) ( $data['categories'] ?? array() );
		$labels     = $core->checks->get_categories();
		$score      = (float) $scan->score;
		$date       = get_date_from_gmt( $scan->completed_at, get_option( 'date_format' ) );

		$severities = array(
			'critical' => array( __( 'Critical', 'catalog-health-scanner-for-woocommerce' ), '#d63638' ),
			'high'     => array( __( 'High', 'catalog-health-scanner-for-woocommerce' ), '#e65054' ),
			'medium'   => array( __( 'Medium', 'catalog-health-scanner-for-woocommerce' ), '#dba617' ),
			'low'      => array( __( 'Low', 'catalog-health-scanner-for-woocommerce' ), '#646970' ),
		);

		// The exact severity counts the dashboard uses: open issues of scored
		// checks only. The PDF and the dashboard describing the same scan with
		// different numbers is the one failure a client-facing report cannot
		// have — every number below flows from these helpers, never from raw
		// issue-table counts.
		$sev_counts = array();
		foreach ( $severities as $severity => $meta ) {
			$sev_counts[ $severity ] = array_sum( $core->issues->count_open_scored_by_category( $severity ) );
		}

		// Badge: severity presence overrides the score band (same rule as the
		// dashboard hero). Drives the label AND the report's accent colour.
		$band        = $core->scores->get_status_badge( $score, $sev_counts['critical'], $sev_counts['high'] );
		$this->band  = $band;
		$this->brand = $branding;

		// Applicability as this scan resolved it (snapshot preferred; live
		// resolution as fallback for scans that predate the snapshot).
		$applicability = ( isset( $data['applicability'] ) && is_array( $data['applicability'] )
			? $data['applicability']
			: $core->applicability->snapshot()
		);

		$this->render_cover( $scan, $score, $band, $branding, $date, $sev_counts, $categories, $labels );
		$this->render_scorecard( $core, $categories, $labels, $severities, $sev_counts, $applicability );
		$this->render_findings( $core, $labels, $severities, $sev_counts );

		return $this->pdf->output();

	}

	/**
	 * Whether a check belongs in this report's findings and counts: its
	 * applicability group is on. Mirrors the dashboard's filtering exactly.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 *
	 * @param   WPFCHS_Check $check
	 * @return  bool
	 */
	protected function is_reportable( $check ) {
		$group = $check->get_group();
		return ( '' === $group || wpfchs()->core->applicability->resolve( $group )['applicable'] );
	}

	/**
	 * Open findings as sortable rows, applicability-filtered, severity first
	 * and reach second — a Low touching 90 products never outranks a
	 * Critical touching one. Store-level checks count as one finding.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 *
	 * @return  array [{check, count, weight}]
	 */
	protected function get_finding_rows() {
		$core           = wpfchs()->core;
		$severity_order = array( 'critical' => 0, 'high' => 1, 'medium' => 2, 'low' => 3 );
		$rows           = array();
		foreach ( $core->issues->count_open_by_check() as $check_id => $count ) {
			$check = $core->checks->get( $check_id );
			if ( ! $check || ! $this->is_reportable( $check ) ) {
				continue;
			}
			$rows[] = array(
				'check' => $check,
				'count' => $count,
				'rank'  => ( $check->is_store_level() ? 1 : $count ),
			);
		}
		usort( $rows, function ( $a, $b ) use ( $severity_order ) {
			$cmp = $severity_order[ $a['check']->get_severity() ] <=> $severity_order[ $b['check']->get_severity() ];
			return ( 0 !== $cmp ? $cmp : $b['rank'] <=> $a['rank'] );
		} );
		return $rows;
	}

	/**
	 * Up to three named products behind a finding, plus "and N more".
	 *
	 * A count with no names is a summary; names are evidence. SKU when the
	 * product has one, the id otherwise.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 *
	 * @param   WPFCHS_Check $check
	 * @param   int          $total Open count for the check.
	 * @return  string
	 */
	protected function example_products( $check, $total ) {
		$issues = wpfchs()->core->issues->query(
			array(
				'check_id' => $check->get_id(),
				'status'   => 'open',
				'limit'    => 3,
			)
		);
		$names = array();
		foreach ( $issues as $issue ) {
			$product_id = (int) $issue->product_id;
			$title      = get_the_title( $product_id );
			if ( '' === $title ) {
				continue;
			}
			$sku     = (string) get_post_meta( (int) $issue->object_id, '_sku', true );
			$names[] = $title . ' (' . ( '' !== $sku ? $sku : '#' . $product_id ) . ')';
		}
		if ( empty( $names ) ) {
			return '';
		}
		$line = implode( ', ', $names );
		if ( $total > count( $names ) ) {
			$line .= ' ' . sprintf(
				/* translators: %s: number of further affected products. */
				__( 'and %s more', 'catalog-health-scanner-for-woocommerce' ),
				number_format_i18n( $total - count( $names ) )
			);
		}
		return $line;
	}

	/**
	 * Draws wrapped text and returns the y cursor after the last line.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 *
	 * @param   float  $x
	 * @param   float  $y
	 * @param   string $text
	 * @param   float  $max_w
	 * @param   float  $size
	 * @param   string $hex
	 * @return  float
	 */
	protected function text_wrap( $x, $y, $text, $max_w, $size, $hex ) {
		$pdf   = $this->pdf;
		$words = preg_split( '/\s+/', (string) $text );
		$line  = '';
		foreach ( $words as $word ) {
			$candidate = ( '' === $line ? $word : $line . ' ' . $word );
			if ( $pdf->width( $candidate, $size ) > $max_w && '' !== $line ) {
				$pdf->text( $x, $y, $line, $size, false, $hex );
				$y    += $size + 3;
				$line  = $word;
			} else {
				$line = $candidate;
			}
		}
		if ( '' !== $line ) {
			$pdf->text( $x, $y, $line, $size, false, $hex );
			$y += $size + 3;
		}
		return $y;
	}

	/**
	 * Cover page: brand, hero score with meter, four stat tiles, severity
	 * chips, and the trend against the previous scan.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 */
	protected function render_cover( $scan, $score, $band, $branding, $date, $sev_counts, $categories, $labels ) {

		$pdf  = $this->pdf;
		$core = wpfchs()->core;
		$this->start_page();

		// Brand band across the top.
		$pdf->rect( 0, 0, WPFCHS_PDF::PAGE_W, 90, '#1d2327' );

		$logo_shift = 0;
		if ( $branding['logo_id'] ) {
			$file = get_attached_file( $branding['logo_id'] );
			if ( $file && file_exists( $file ) ) {
				$blob = file_get_contents( $file ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- Local attachment file read, not a remote URL.
				if ( $blob && $pdf->image( $blob, 60, 26, 110 ) ) {
					$logo_shift = 130;
				}
			}
		}
		$pdf->text( 60 + $logo_shift, 44, $branding['agency_name'], 16, true, '#ffffff' );
		$pdf->text( 60 + $logo_shift, 64, __( 'Catalog Health Audit', 'catalog-health-scanner-for-woocommerce' ), 11, false, '#c3c4c7' );

		/**
		 * The store label printed on the report header. Filterable so demo or
		 * staging environments can present a client-appropriate name instead
		 * of an internal hostname.
		 *
		 * @since 1.0.0
		 *
		 * @param string $label Defaults to the site host.
		 */
		$site_label = apply_filters( 'wpfchs_report_site_label', (string) wp_parse_url( home_url(), PHP_URL_HOST ) );
		$pdf->text( WPFCHS_PDF::PAGE_W - 60, 54, $site_label . '  ·  ' . $date, 10, false, '#c3c4c7', 'right' );

		// Hero score.
		$pdf->text( 60, 190, wc_format_decimal( $score, 0 ) . '%', 84, true, $band['color'] );
		$pdf->text( 250, 150, $band['label'], 20, true, $band['color'] );
		$pdf->text( 250, 174, sprintf(
			/* translators: %1$s: products scanned, %2$s: issues found. */
			__( '%1$s products scanned  ·  %2$s open issues', 'catalog-health-scanner-for-woocommerce' ),
			number_format_i18n( (int) $scan->products_scanned ),
			number_format_i18n( $core->issues->count_open_effective() )
		), 11, false, '#646970' );

		$profiles = $core->profiles->get_all();
		$pdf->text( 250, 192, sprintf(
			/* translators: %s: scan profile name. */
			__( 'Profile: %s', 'catalog-health-scanner-for-woocommerce' ),
			( $profiles[ $scan->profile ]['label'] ?? $scan->profile )
		), 11, false, '#646970' );

		// Anything excluded from the score has to be declared on the cover.
		// This document gets handed to clients; a score that quietly omits
		// ignored findings or skipped products would misrepresent the store.
		$ignored = $core->issues->count( array( 'status' => 'ignored' ) );
		$skipped = $core->scanner->get_skipped_count( $scan );
		$caveats = array();
		if ( $ignored > 0 ) {
			$caveats[] = sprintf(
				/* translators: %s: number of ignored issues. */
				_n( '%s issue ignored', '%s issues ignored', $ignored, 'catalog-health-scanner-for-woocommerce' ),
				number_format_i18n( $ignored )
			);
		}
		if ( $skipped > 0 ) {
			$caveats[] = sprintf(
				/* translators: %s: number of products skipped. */
				_n( '%s product not checked', '%s products not checked', $skipped, 'catalog-health-scanner-for-woocommerce' ),
				number_format_i18n( $skipped )
			);
		}
		if ( ! empty( $caveats ) ) {
			$pdf->text(
				250,
				210,
				__( 'Excluded from this score:', 'catalog-health-scanner-for-woocommerce' ) . ' ' . implode( ', ', $caveats ),
				9,
				false,
				'#b26200'
			);
		}

		// Score meter.
		$pdf->rect( 60, 210, 475, 10, '#e5e5e6' );
		$pdf->rect( 60, 210, 475 * max( 0, min( 1, $score / 100 ) ), 10, $band['color'] );

		// Stat tiles. On a first scan there is no delta to show — "Baseline
		// set" is the honest tile, not "+0.0 vs last scan".
		$critical  = $sev_counts['critical'];
		$previous  = $core->schedule->get_previous_score( (int) $scan->id );
		$delta     = ( null !== $previous ? round( $score - $previous, 1 ) : null );
		$unchanged = ( null !== $delta && abs( $delta ) < 0.05 );

		if ( null === $delta ) {
			$delta_str = '—';
			$delta_lbl = __( 'Baseline set', 'catalog-health-scanner-for-woocommerce' );
			$delta_col = '#646970';
		} elseif ( $unchanged ) {
			// "+0.0" reads as a measurement error rather than a result.
			$delta_str = '—';
			$delta_lbl = __( 'No change', 'catalog-health-scanner-for-woocommerce' );
			$delta_col = '#646970';
		} else {
			$delta_str = ( $delta > 0 ? '+' : '' ) . wc_format_decimal( $delta, 1 );
			$delta_lbl = __( 'vs last scan', 'catalog-health-scanner-for-woocommerce' );
			$delta_col = ( $delta > 0 ? '#00812c' : '#d63638' );
		}

		$applicable = 0;
		foreach ( $categories as $cat ) {
			$applicable++;
		}

		$tiles = array(
			array( number_format_i18n( (int) $scan->products_scanned ), __( 'Products', 'catalog-health-scanner-for-woocommerce' ), '#1d2327' ),
			array( number_format_i18n( $core->issues->count_open_effective() ), __( 'Open issues', 'catalog-health-scanner-for-woocommerce' ), '#1d2327' ),
			array( number_format_i18n( $critical ), __( 'Critical', 'catalog-health-scanner-for-woocommerce' ), ( $critical > 0 ? '#d63638' : '#00812c' ) ),
			array( $delta_str, $delta_lbl, $delta_col ),
		);
		$tile_w = ( 475 - 3 * 13 ) / 4;
		$tx     = 60;
		foreach ( $tiles as $tile ) {
			$pdf->rect( $tx, 250, $tile_w, 70, '#f6f7f7' );
			$pdf->rect( $tx, 250, $tile_w, 3, $band['color'] );
			$pdf->text( $tx + $tile_w / 2, 292, (string) $tile[0], 26, true, $tile[2], 'center' );
			$pdf->text( $tx + $tile_w / 2, 310, (string) $tile[1], 9, false, '#646970', 'center' );
			$tx += $tile_w + 13;
		}

		// Severity chips.
		$pdf->text( 60, 360, __( 'Open issues by severity', 'catalog-health-scanner-for-woocommerce' ), 13, true );
		$sx = 60;
		foreach ( array(
			'critical' => array( __( 'Critical', 'catalog-health-scanner-for-woocommerce' ), '#d63638' ),
			'high'     => array( __( 'High', 'catalog-health-scanner-for-woocommerce' ), '#e65054' ),
			'medium'   => array( __( 'Medium', 'catalog-health-scanner-for-woocommerce' ), '#dba617' ),
			'low'      => array( __( 'Low', 'catalog-health-scanner-for-woocommerce' ), '#646970' ),
		) as $severity => $meta ) {
			$pdf->rect( $sx, 375, 11, 11, $meta[1] );
			$pdf->text( $sx + 17, 384, $meta[0] . ': ' . number_format_i18n( $sev_counts[ $severity ] ), 11 );
			$sx += 118;
		}

		$y = 412;

		// The critical banner — the dashboard's red banner, on paper. When
		// products cannot be bought, that is the first thing the reader sees,
		// not a footnote below a count-sorted list.
		if ( $sev_counts['critical'] > 0 ) {
			$by_cat = $core->issues->count_open_scored_by_category( 'critical' );
			$pdf->rect( 60, $y - 16, 475, 46, '#fcf0f1' );
			$pdf->rect( 60, $y - 16, 4, 46, '#d63638' );
			$pdf->text( 76, $y, sprintf(
				/* translators: %s: number of critical issues. */
				_n( '%s critical issue is costing you sales right now.', '%s critical issues are costing you sales right now.', $sev_counts['critical'], 'catalog-health-scanner-for-woocommerce' ),
				number_format_i18n( $sev_counts['critical'] )
			), 12, true, '#8a1f21' );
			$chips = array();
			foreach ( $by_cat as $category_id => $count ) {
				$chips[] = ( $labels[ $category_id ] ?? $category_id ) . ' ' . number_format_i18n( $count );
			}
			$pdf->text( 76, $y + 17, implode( '  ·  ', $chips ), 9, false, '#8a1f21' );
			$y += 52;
		}

		// What to fix first: severity before reach. A Low finding on ninety
		// products never outranks a Critical on one.
		$rows = $this->get_finding_rows();
		if ( ! empty( $rows ) ) {
			$pdf->text( 60, $y + 12, __( 'What to fix first', 'catalog-health-scanner-for-woocommerce' ), 13, true );
			$y += 34;
			foreach ( array_slice( $rows, 0, 5 ) as $row ) {
				$sev = $row['check']->get_severity();
				$col = array( 'critical' => '#d63638', 'high' => '#e65054', 'medium' => '#dba617', 'low' => '#646970' )[ $sev ] ?? '#646970';
				$pdf->rect( 60, $y - 8, 8, 8, $col );
				$pdf->text( 76, $y, $row['check']->get_label(), 11 );
				$reach = (
					$row['check']->is_store_level() ?
					sprintf(
						/* translators: %s: number of affected products. */
						__( 'store-wide (%s products)', 'catalog-health-scanner-for-woocommerce' ),
						number_format_i18n( $row['count'] )
					) :
					sprintf(
						/* translators: %s: number of affected products. */
						_n( '%s product', '%s products', $row['count'], 'catalog-health-scanner-for-woocommerce' ),
						number_format_i18n( $row['count'] )
					)
				);
				$pdf->text( 535, $y, $reach, 10, false, '#646970', 'right' );
				$y += 22;
			}
		}

		$this->footer();

	}

	/**
	 * Scorecard page: per-category bars and the severity distribution.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 */
	protected function render_scorecard( $core, $categories, $labels, $severities, $sev_counts, $applicability = array() ) {

		$pdf = $this->pdf;
		$this->start_page( __( 'Category scorecard', 'catalog-health-scanner-for-woocommerce' ) );
		$y = 120;

		$crit_by_cat = $core->issues->count_open_scored_by_category( 'critical' );
		$high_by_cat = $core->issues->count_open_scored_by_category( 'high' );

		foreach ( $labels as $category_id => $label ) {
			if ( ! isset( $categories[ $category_id ] ) ) {
				continue;
			}
			$earned   = (float) $categories[ $category_id ]['earned'];
			$possible = (float) $categories[ $category_id ]['possible'];
			// Bar colour follows the score; severity gets its own chip, so a
			// strong category with one critical does not read as a failing one.
			$cat_band = $core->scores->get_category_band( $earned, $possible );
			$chip     = $core->scores->get_severity_chip(
				(int) ( $crit_by_cat[ $category_id ] ?? 0 ),
				(int) ( $high_by_cat[ $category_id ] ?? 0 )
			);
			$percent  = ( $possible > 0 ? $earned / $possible : 1 );

			$pdf->text( 60, $y, $label, 11, true );
			if ( $chip ) {
				$pdf->text( 190, $y, $chip['label'], 9, true, $chip['color'] );
			}
			$pdf->text( 320, $y, wc_format_decimal( $earned, 1 ) . ' / ' . wc_format_decimal( $possible, 0 ), 11, false, '#646970', 'right' );
			$pdf->rect( 340, $y - 8, 195, 8, '#e5e5e6' );
			$pdf->rect( 340, $y - 8, 195 * max( 0, min( 1, $percent ) ), 8, $cat_band['color'] );
			$y += 26;
		}

		// Anything the scan excluded is declared, with its reason — the same
		// grey cards the dashboard shows. Silently dropping a category would
		// let a reader conclude the score was inflated by omission.
		$excluded = array();
		foreach ( (array) $applicability as $group => $state ) {
			if ( empty( $state['applicable'] ) ) {
				$excluded[] = array( $core->applicability->get_group_label( $group ), (string) ( $state['reason'] ?? '' ) );
			} elseif ( empty( $state['scored'] ) ) {
				$excluded[] = array(
					$core->applicability->get_group_label( $group ),
					__( 'Reported, but excluded from the score at your request.', 'catalog-health-scanner-for-woocommerce' ),
				);
			}
		}
		if ( ! empty( $excluded ) ) {
			$y += 16;
			$pdf->text( 60, $y, __( 'Excluded from this audit', 'catalog-health-scanner-for-woocommerce' ), 14, true );
			$y += 8;
			$pdf->text( 60, $y + 10, __( 'These checks were not run against your store, and neither side of the score includes them.', 'catalog-health-scanner-for-woocommerce' ), 9, false, '#646970' );
			$y += 28;
			foreach ( $excluded as $row ) {
				$y = $this->ensure_space( $y, 20 );
				$pdf->rect( 60, $y - 7, 7, 7, '#c3c4c7' );
				$pdf->text( 74, $y, $row[0], 10, true, '#646970' );
				$y = $this->text_wrap( 74, $y + 14, $row[1], 440, 9, '#8c8f94' );
				$y += 8;
			}
		}

		// The severity breakdown lives on page 1 beside the headline figures.
		// Repeating it here told the reader the same thing twice.

		$this->footer();

	}

	/**
	 * Findings pages: every check with open issues, grouped by category,
	 * auto-paginated. This is the "cover all findings" section.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 */
	protected function render_findings( $core, $labels, $severities, $sev_counts = array() ) {

		$pdf        = $this->pdf;
		$last       = $core->admin->get_last_scan_data();
		$cat_scores = $last['categories'];

		// Applicability-filtered, severity-sorted rows (same source as the
		// cover's fix-first list), grouped by category.
		$all_rows    = $this->get_finding_rows();
		$by_category = array();
		foreach ( $all_rows as $row ) {
			$by_category[ $row['check']->get_category() ][] = $row;
		}

		$this->start_page( __( 'All findings', 'catalog-health-scanner-for-woocommerce' ) );
		$y = 120;

		if ( empty( $by_category ) ) {
			$pdf->text( 60, $y, __( 'No open issues. Every applicable check passed.', 'catalog-health-scanner-for-woocommerce' ), 12, false, '#00812c' );
			$this->footer();
			return;
		}

		foreach ( $labels as $category_id => $label ) {

			if ( empty( $by_category[ $category_id ] ) ) {
				continue;
			}

			$y = $this->ensure_space( $y, 46 );

			// Category heading with its score fraction.
			$pdf->text( 60, $y, $label, 14, true );
			if ( isset( $cat_scores[ $category_id ] ) ) {
				$pdf->text( 535, $y, wc_format_decimal( $cat_scores[ $category_id ]['earned'], 1 ) . ' / ' . wc_format_decimal( $cat_scores[ $category_id ]['possible'], 0 ), 11, false, '#646970', 'right' );
			}
			$y += 8;
			$pdf->rect( 60, $y, 475, 0.7, '#dcdcde' );
			$y += 18;

			foreach ( $by_category[ $category_id ] as $row ) {

				$check   = $row['check'];
				$sev     = $check->get_severity();
				$col     = $severities[ $sev ][1];
				$serious = in_array( $sev, array( 'critical', 'high' ), true );

				// Row + explanation + examples move to the next page as one
				// unit; a finding split from its evidence reads as two.
				$y = $this->ensure_space( $y, ( $serious ? 68 : 22 ) );

				$pdf->rect( 60, $y - 8, 8, 8, $col );
				$pdf->text( 76, $y, $check->get_label(), 10, true );
				$pdf->text( 470, $y, $severities[ $sev ][0], 9, false, '#646970' );
				$count_str = (
					$check->is_store_level() ?
					__( 'Store-wide', 'catalog-health-scanner-for-woocommerce' ) :
					number_format_i18n( $row['count'] )
				);
				$pdf->text( 535, $y, $count_str, 10, true, '#1d2327', 'right' );
				$y += 14;

				// The plain-language impact line — the register the reader
				// bought this report for, not the internal check name alone.
				if ( $serious ) {
					$explanation = $check->get_explanation();
					if ( $check->is_store_level() ) {
						$explanation .= ' ' . sprintf(
							/* translators: %s: number of affected products. */
							__( 'One store-level cause — currently reaching %s products.', 'catalog-health-scanner-for-woocommerce' ),
							number_format_i18n( $row['count'] )
						);
					}
					$y = $this->text_wrap( 76, $y, $explanation, 440, 9, '#646970' );

					// Evidence: named products, not just a count.
					if ( ! $check->is_store_level() ) {
						$examples = $this->example_products( $check, $row['count'] );
						if ( '' !== $examples ) {
							$y = $this->text_wrap( 76, $y + 2, __( 'e.g.', 'catalog-health-scanner-for-woocommerce' ) . ' ' . $examples, 440, 9, '#8c8f94' );
						}
					}
					$y += 10;
				} else {
					$y += 8;
				}
			}
			$y += 14;
		}

		// Closing block: where the reader goes from here. A report that stops
		// mid-table leaves the next step to guesswork.
		$critical_total = (int) ( $sev_counts['critical'] ?? 0 );
		$top            = ( ! empty( $all_rows ) ? $all_rows[0] : null );

		$y = $this->ensure_space( $y, 96 );
		$pdf->rect( 60, $y - 4, 475, 0.7, '#dcdcde' );
		$y += 18;
		$pdf->text( 60, $y, __( 'Where to go from here', 'catalog-health-scanner-for-woocommerce' ), 14, true );
		$y += 20;

		if ( $critical_total > 0 ) {
			$y = $this->text_wrap( 60, $y, sprintf(
				/* translators: %s: number of critical issues. */
				_n( '%s critical issue is open. Products affected by critical issues cannot be bought, mislead customers, or lose money on every order — resolve these before anything else in this report.', '%s critical issues are open. Products affected by critical issues cannot be bought, mislead customers, or lose money on every order — resolve these before anything else in this report.', $critical_total, 'catalog-health-scanner-for-woocommerce' ),
				number_format_i18n( $critical_total )
			), 475, 10, '#1d2327' );
		} else {
			$y = $this->text_wrap( 60, $y, __( 'No critical issues are open. Work down the findings above in order — each list is already sorted by what costs you most.', 'catalog-health-scanner-for-woocommerce' ), 475, 10, '#1d2327' );
		}

		if ( $top ) {
			$y += 6;
			$y = $this->text_wrap( 60, $y, sprintf(
				/* translators: %1$s: check name, %2$s: category name. */
				__( 'Start with: %1$s — open WooCommerce › Catalog Health › %2$s to see every affected product with actions beside it.', 'catalog-health-scanner-for-woocommerce' ),
				$top['check']->get_label(),
				( $labels[ $top['check']->get_category() ] ?? $top['check']->get_category() )
			), 475, 10, '#646970' );
		}

		$this->footer();

	}

	/**
	 * Starts a new page: top brand rule, page counter, optional section title.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 *
	 * @param   string $title
	 */
	protected function start_page( $title = '' ) {
		$this->pdf->add_page();
		$this->page++;
		$this->pdf->rect( 0, 0, WPFCHS_PDF::PAGE_W, 8, $this->band['color'] );
		if ( '' !== $title ) {
			$this->pdf->text( 60, 70, $title, 20, true );
		}
	}

	/**
	 * Ensures $needed points of vertical space remain; otherwise closes the
	 * page and starts a continuation.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 *
	 * @param   float $y
	 * @param   float $needed
	 * @return  float New y cursor.
	 */
	protected function ensure_space( $y, $needed ) {
		if ( $y + $needed > WPFCHS_PDF::PAGE_H - 80 ) {
			$this->footer();
			$this->start_page();
			return 100;
		}
		return $y;
	}

	/**
	 * footer.
	 *
	 * @version 1.0.0
	 * @since   1.0.0
	 */
	protected function footer() {
		$pdf = $this->pdf;
		$pdf->rect( 60, WPFCHS_PDF::PAGE_H - 60, WPFCHS_PDF::PAGE_W - 120, 0.7, '#dcdcde' );
		$pdf->text( 60, WPFCHS_PDF::PAGE_H - 42, $this->brand['footer'], 9, false, '#646970' );
		$pdf->text( WPFCHS_PDF::PAGE_W - 60, WPFCHS_PDF::PAGE_H - 42, (string) $this->page, 9, false, '#646970', 'right' );
	}

}

endif;

return new WPFCHS_Report();
